/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana07.Trabajo;

import java.util.ArrayList;

/**
 *
 * @author Ario1
 */
class Estudiante {

    private int id;
    private int nota1;
    private int nota2;
    private int nota3;
    private double promedio;

    public Estudiante(int id, int nota1, int nota2, int nota3) {
        this.id = id;
        this.nota1 = nota1;
        this.nota2 = nota2;
        this.nota3 = nota3;
        this.promedio = (this.nota1 + this.nota2 + this.nota3) / 3;
    }

    public int getNota1() {
        return nota1;
    }

    public void setNota1(int nota1) {
        this.nota1 = nota1;
    }

    public int getNota2() {
        return nota2;
    }

    public void setNota2(int nota2) {
        this.nota2 = nota2;
    }

    public int getNota3() {
        return nota3;
    }

    public void setNota3(int nota3) {
        this.nota3 = nota3;
    }

    public double getPromedio() {
        return promedio;
    }

    public void setPromedio(double promedio) {
        this.promedio = promedio;
    }

}

public class Ejercicio02 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio02
     */
    ArrayList<Estudiante> estu;
    
    public Ejercicio02() {
        estu = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlPromExamen3 = new javax.swing.JLabel();
        jlMayorPromedio = new javax.swing.JLabel();
        jlNumestudiante = new javax.swing.JLabel();
        jlNumaprovados = new javax.swing.JLabel();
        jlNumDesaprovados = new javax.swing.JLabel();
        jlNumdesaExamen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de orden:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Examen 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setText("Examen 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setText("Examen 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 30, -1));
        jPanel1.add(txtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, -1));

        txtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 70, -1));
        jPanel1.add(txtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, -1));

        jLabel5.setText("Promedio del Aula Examen 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel6.setText("Mayor Promedio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel7.setText("Nº de estudiante");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel8.setText("Nº de aprobados");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel9.setText("Nª de Desaprovados");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel10.setText("Nº de Desaprovados Examen 1");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jlPromExamen3.setText("0.0");
        jPanel1.add(jlPromExamen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jlMayorPromedio.setText("0.0");
        jPanel1.add(jlMayorPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jlNumestudiante.setText("0");
        jPanel1.add(jlNumestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jlNumaprovados.setText("0");
        jPanel1.add(jlNumaprovados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jlNumDesaprovados.setText("0");
        jPanel1.add(jlNumDesaprovados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jlNumdesaExamen1.setText("0");
        jPanel1.add(jlNumdesaExamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        int n1 = Integer.parseInt(txtn1.getText());
        int n2 = Integer.parseInt(txtn2.getText());
        int n3 = Integer.parseInt(txtn3.getText());
        int id = Integer.parseInt(txtID.getText());
        try {
            estu.add(new Estudiante(id, n1, n2, n3));
        } catch (Exception e) {
            System.out.println("error");
        }
        
        
        
        txtn1.setText("");
        txtn2.setText("");
        txtn3.setText("");
        txtID.setText("");
        txtID.requestFocus();


    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn2ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        jlPromExamen3.setText(String.valueOf(PromedioExame03()));
        jlMayorPromedio.setText(String.valueOf(PromedioMayor()));
        jlNumestudiante.setText(String.valueOf(estu.size()));
        jlNumaprovados.setText(String.valueOf(NumProvados()));
        jlNumDesaprovados.setText(String.valueOf(NumDesaprovados()));
        jlNumdesaExamen1.setText(String.valueOf(NumDesaprovadosExamen01()));
        txtn1.setText(" ");
        txtn2.setText(" ");
        txtn3.setText(" ");

    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    double PromedioExame03() {
        double prom = 0;
        double suma= 0;
        for (int i = 0; i < estu.size(); i++) {
            suma += (double) estu.get(i).getNota3();
        }
        prom=suma/estu.size()+1;
        return prom ;
    }

    double PromedioMayor() {
        double prom = 0;
        for (int i = 0; i < estu.size(); i++) {
            for (int j = 0; j < estu.size(); j++) {
                if (estu.get(i).getPromedio() > estu.get(j).getPromedio()) {
                    prom = estu.get(i).getPromedio();
                }
            }
        }
        return prom;
    }

    int NumProvados() {
        int con = 0;
        for (int i = 0; i < estu.size(); i++) {
            if (estu.get(i).getPromedio() > 10) {
                con++;
            }
        }
        return con;
    }

    int NumDesaprovados() {
        int con = 0;
        for (int i = 0; i < estu.size(); i++) {
            if (estu.get(i).getPromedio() <= 10) {
                con++;
            }
        }
        return con;
    }

    int NumDesaprovadosExamen01() {
        int con = 0;
        for (int i = 0; i < estu.size(); i++) {
            if (estu.get(i).getNota1() <= 10) {
                con++;
            }
        }
        return con;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlMayorPromedio;
    private javax.swing.JLabel jlNumDesaprovados;
    private javax.swing.JLabel jlNumaprovados;
    private javax.swing.JLabel jlNumdesaExamen1;
    private javax.swing.JLabel jlNumestudiante;
    private javax.swing.JLabel jlPromExamen3;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    // End of variables declaration//GEN-END:variables
}
