/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana07.Trabajo;

import java.util.ArrayList;

/**
 *
 * @author Ario1
 */
class Departamento {

    private double dulces;
    private double Bebidas;
    private double Conservas;
    int mes;

    public Departamento(double dulces, double Bebidas, double Conservas, int p) {
        this.dulces = dulces;
        this.Bebidas = Bebidas;
        this.Conservas = Conservas;
        this.mes = p;
    }

    public int getMes() {
        return mes;
    }

    public double getDulces() {
        return dulces;
    }

    public double getBebidas() {
        return Bebidas;
    }

    public double getConservas() {
        return Conservas;
    }

}

public class Ejercicio03 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio03
     */
    ArrayList<Departamento> produc;
    double menor = 99999999;

    public Ejercicio03() {
        initComponents();
        produc = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtdulces = new javax.swing.JTextField();
        txtbebidas = new javax.swing.JTextField();
        txtconservas = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMayorDulces = new javax.swing.JTextField();
        txtPromedioAnualBebidas = new javax.swing.JTextField();
        txtMenorCostoBebidad = new javax.swing.JTextField();
        txtMayorProduccionEnAgosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MES:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setText("DULCES:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 94, -1, -1));

        jLabel3.setText("BEBIDAS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 136, -1, -1));

        jLabel4.setText("CONSERVAS:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 174, -1, -1));

        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, -1));
        jPanel1.add(txtdulces, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 90, 140, -1));

        txtbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbebidasActionPerformed(evt);
            }
        });
        jPanel1.add(txtbebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        txtconservas.setText("     ");
        jPanel1.add(txtconservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 170, 130, -1));

        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel5.setText("Mes de mayor produccion de dulces: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setText("Promedio Anual de los costos de produccion de bebidas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7.setText("En que mes se registro el menor costo de P.Bebidas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel8.setText("CUal fue el departamento de menor produccion en agosto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 20));

        txtMayorDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMayorDulcesActionPerformed(evt);
            }
        });
        jPanel1.add(txtMayorDulces, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 210, -1));

        txtPromedioAnualBebidas.setText("                     ");
        txtPromedioAnualBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedioAnualBebidasActionPerformed(evt);
            }
        });
        jPanel1.add(txtPromedioAnualBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 210, -1));

        txtMenorCostoBebidad.setText("                        ");
        jPanel1.add(txtMenorCostoBebidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 220, -1));

        txtMayorProduccionEnAgosto.setText("                     ");
        jPanel1.add(txtMayorProduccionEnAgosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void txtbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbebidasActionPerformed

    private void txtPromedioAnualBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedioAnualBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedioAnualBebidasActionPerformed

    private void txtMayorDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMayorDulcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMayorDulcesActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        double dul = Double.parseDouble(txtdulces.getText());
        double beb = Double.parseDouble(txtbebidas.getText());
        double cons = Double.parseDouble(txtconservas.getText());
        int mes = Integer.parseInt(txtMes.getText());
        produc.add(new Departamento(dul, beb, cons, mes));
        txtdulces.setText("");
        txtbebidas.setText("");
        txtconservas.setText("");
        txtMes.setText("");
        txtMes.requestFocus();

    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        txtMayorDulces.setText(MAyorProducDulce());
        txtPromedioAnualBebidas.setText(String.valueOf(PromedioAnual()));
        txtMenorCostoBebidad.setText(MenorProducDulce());
        txtMayorProduccionEnAgosto.setText(MenorProduCAgosto());
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    String MAyorProducDulce() {
        String cad = "";
        for (int i = 0; i < produc.size(); i++) {
            for (int j = 0; j < produc.size(); j++) {
                if (produc.get(i).getDulces() > produc.get(j).getDulces()) {
                    cad = MES(produc.get(i).getMes());
                }else{
                    cad=MES(produc.get(i).getMes());
                }
            }
        }
        return cad;
    }

    String MES(int x) {
        String mes[] = {"Enero", "febrero", "marzo", "Abril", "mayo", "junio", "julio",
            "agosto", "setiembre", "obtubre", "noviembre", "diciembre"};
        return mes[x + 1];
    }

    double PromedioAnual() {
        double prom = 0;
        double suma = 0;
        for (int i = 0; i < produc.size(); i++) {
            suma += produc.get(i).getBebidas();
        }
        prom = suma / 12;
        return prom;
    }

    String MenorProducDulce() {
        String cad = "";
        for (int i = 0; i < produc.size(); i++) {
            if (produc.get(i).getBebidas() < menor) {
                menor=produc.get(i).getBebidas();
                cad = MES(produc.get(i).getMes());
            }
        }
        return cad;
    }
    String MenorProduCAgosto(){
        String cad="";
        for (int i = 0; i < produc.size(); i++) {
            if (produc.get(i).getMes()==6) {
                if (produc.get(i).getDulces()<produc.get(i).getBebidas()&&
                        produc.get(i).getDulces()<produc.get(i).getConservas()) {
                     cad="dulces";
                    
                }else if (produc.get(i).getBebidas()<produc.get(i).getDulces()&&
                        produc.get(i).getBebidas()<produc.get(i).getConservas()) {
                    cad="bebidas";
                    
                }else{
                    cad= "conervas";
                }
                break;
            }
        }
        return cad;
    }
    

 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMayorDulces;
    private javax.swing.JTextField txtMayorProduccionEnAgosto;
    private javax.swing.JTextField txtMenorCostoBebidad;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPromedioAnualBebidas;
    private javax.swing.JTextField txtbebidas;
    private javax.swing.JTextField txtconservas;
    private javax.swing.JTextField txtdulces;
    // End of variables declaration//GEN-END:variables
}
