/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana07.practica;

import java.util.HashSet;

/**
 *
 * @author Ario1
 */
public class Ejercicio02 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio02
     */
    int ma,me,sa,sb;
    HashSet<Integer> lista;
    public Ejercicio02() {
        initComponents();
        lista= new HashSet<>();
        ma=1;
        me=100;
        sa=0;
        sb=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLNnumeros = new javax.swing.JLabel();
        txtNnumeros = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        lbnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txANumeros = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNnumeros.setText("Ingrese N numeros: ");
        jPanel1.add(jLNnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 50, -1, -1));

        txtNnumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNnumerosActionPerformed(evt);
            }
        });
        jPanel1.add(txtNnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 46, 102, -1));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 110, -1, -1));

        lbnMostrar.setText("Mostrar");
        lbnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(lbnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 110, -1, -1));

        txANumeros.setColumns(20);
        txANumeros.setRows(5);
        jScrollPane1.setViewportView(txANumeros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 160, -1, 226));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNnumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNnumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNnumerosActionPerformed

    private void lbnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbnMostrarActionPerformed
        encontrar();
        txANumeros.append("#=====================================#\n");
        txANumeros.append("max: "+ma+" En la posicion "+sa+"\n");
        txANumeros.append("min: "+me+" En la posicion "+sb+"\n");
    }//GEN-LAST:event_lbnMostrarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
            int n=Integer.parseInt(txtNnumeros.getText());
        for (int i = 0; i < n; i++) {
            lista.add(aleatorio(1, 100));
        }
        txANumeros.setText(cadnumero());
    }//GEN-LAST:event_btnGenerarActionPerformed
    int aleatorio(int min,int max){
        return (int)((max-min+1)*Math.random()+min);
    }
    String cadnumero(){
        String cad="";
        for (Integer e : lista) {
            cad+=e+"\n";
        }
        return cad;
    }
    void encontrar(){
        int cont=0;
        for (Integer i : lista) {
            if (ma<=i) {
                ma=i;
                sa=cont;
            }else if (me>=i) {
                me=i;
                sb=cont;
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLNnumeros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lbnMostrar;
    private javax.swing.JTextArea txANumeros;
    private javax.swing.JTextField txtNnumeros;
    // End of variables declaration//GEN-END:variables
}
