/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana07.practica;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ario1
 */
public class Ejercicio01 extends javax.swing.JFrame {

    ArrayList<Double> lista = new ArrayList<>();

    /**
     * Creates new form Ejercicio01
     */
    public Ejercicio01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLnota = new javax.swing.JLabel();
        txtnota = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxAnotas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlNnotas = new javax.swing.JLabel();
        jlPromedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLnota.setText("Nota :");
        jPanel1.add(JLnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 37, -1, -1));

        txtnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 33, 126, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        TxAnotas.setColumns(20);
        TxAnotas.setRows(5);
        jScrollPane1.setViewportView(TxAnotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 240, 230));

        jLabel1.setText("Nro Notas:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel2.setText("Promedio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jlNnotas.setText("0");
        jPanel1.add(jlNnotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 50, 20));

        jlPromedio.setText("0.0");
        jlPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPromedioMouseClicked(evt);
            }
        });
        jPanel1.add(jlPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotaActionPerformed

    }//GEN-LAST:event_txtnotaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        

        double nu = Double.parseDouble(txtnota.getText());

        lista.add(nu);

        txtnota.setText("");
        txtnota.requestFocus();
        jlNnotas.setText(String.valueOf(lista.size()));
        
        

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        TxAnotas.setText("");
        TxAnotas.setText(Nnumeros());
        double promedio = acunumero()/lista.size();
        jlPromedio.setText(String.valueOf(promedio));
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jlPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlPromedioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlPromedioMouseClicked

    /**
     * @param args the command line arguments
     */
    String Nnumeros(){
        String cad=" ";
        for (Double e: lista) {
            cad =cad+e+"\n";
        }
        return cad;
    }
    double acunumero(){
        double suma=0.0;
        for (Double e : lista) {
            suma+=e;
        }
        return suma;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnota;
    private javax.swing.JTextArea TxAnotas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNnotas;
    private javax.swing.JLabel jlPromedio;
    private javax.swing.JTextField txtnota;
    // End of variables declaration//GEN-END:variables
}
